import initScrollSuave from "./modules/scroll-suave.js";
import initAnimacaoScroll from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion.js';
import initTabNav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTolltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initFuncionamento from "./modules/funcionamento.js";

initAccordion();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initModal();
initTolltip();
initDropdownMenu();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();